package com.neuedu.dao;

import com.neuedu.pojo.Cart;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    Cart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    List<Cart> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_cart
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Cart record);

    Cart selectCartByUseridProductid(@Param("userId") Integer userId,
                                     @Param("productId") Integer productId);

    /**
     * 查询购物车信息
     */
    List<Cart> selectCartByUserid(Integer userId);

    /**
     * 查询购物车信息是否全选
     * 1选中0未选中
     */
    int isCheckedAll(Integer userId);

    /**
     * 删除购物车商品
     */
    int deleteByUseridProductid(@Param("userId") Integer userId,
                                @Param("productIdList") List<Integer> productIdList);

    /**
     * 购物车商品是否选中
     */
    int selectOrUnselectProduct(@Param("userId") Integer userId,
                                @Param("productId")Integer productId,
                                @Param("check")Integer check);

    /**
     * 统计购物车中产品数量
     */
    int get_cart_product_count(Integer userId);

    /**
     * 查询用户选中的商品
     */
    List<Cart> findCartListByUseridChecked(Integer userId);

    /**
     * 批量删除购物车商品
     */
    int batchDelete(List<Cart> cartList);


}