package com.neuedu.dao;

import com.neuedu.pojo.UserInfo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    UserInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    List<UserInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserInfo record);

    /**
     * 校验用户名是否存在
     */
    int checkusername(String username);

    /**
     * 校验邮箱是否存在
     */
    int checkEmail(String email);

    /**
     *查询用户信息
     */
    UserInfo selectuserInfoByusernameAndpassword(@Param("username") String username, @Param("password") String password);

    /**
     * 根据用户名查询密保问题
     */
    String selectQuestionByUsername(String username);

    /**
     * 根据用户名校验密码
     */
    int selectByUsernameQuestionAnswer(@Param("username")String username,@Param("question")String question,@Param("answer")String answer);

    /**
     * 重置密码
     */
    int updateUsernamePassword(@Param("username") String username,
                               @Param("password") String passwordnew);

    int updateUserByEmailPhoneQuestionAnswer(UserInfo userInfo);

    /**
     * 自动登录
     */
    int updateTokenByUserid(@Param("userId") Integer userId,
                            @Param("token") String token);

    /**
     * 查询token
     */
    UserInfo findUserinfoByToken(String token);

}